[package]
name = "charon-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
evdev.workspace = true
serde.workspace = true
tokio.workspace = true
uuid.workspace = true
maiko.workspace = true
